name: extension_flutter_tools
description: Extensions and functions useful for a flutter app.
version: 1.5.0

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  intl: '>=0.18.0 <=0.19.0'

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
