name: extension_flutter_tools
description: Extensions and functions useful for a flutter app.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
