name: extension_flutter_tools
description: Extensions and functions useful for a flutter app.
version: 1.6.1
repository: https://github.com/maxbritto/extension_flutter_tools

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  intl: '>=0.18.0 <=0.20.0'
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
