name: extension_flutter_tools
description: Extensions and functions useful for a flutter app.
version: 1.1.1

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
